development:
  adapter: postgresql
  encoding: unicode
  database: mapit_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mapit_test
  pool: 5
  username: ubuntu
  password:

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
