development:
  adapter: postgresql
  encoding: unicode
  database: mapit_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mapit_test
  pool: 5
  username: ubuntu
  password:
